apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: logstash

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: grafana

